config/routes.rb
Rails.application.routes.draw do

  get 'users/show_user'
  get 'users/show_admin'
  get 'admin_edit', to: 'tasks#admin_edit'
  get 'admin_new', to: 'tasks#admin_new'
  get 'admin_show', to: 'tasks#admin_show'
  post 'state_change', to: 'tasks#state_change'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'tasks#index'
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  validates :name, presence: true
  enum state: { 'new task' => 1, 'start' => 2, 'finished' => 3 }
  validates :state, inclusion: { in: Task.states.keys }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tasks, dependent: :destroy
  validates :email, uniqueness: true
  enum role: { 'admin' => 1, 'user' => 2 }
  validates :role, inclusion: { in: User.roles.keys }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize_user

  protected

    def authorize_user
      @current_user = User.find_by(id: session[:user_id])
      unless @current_user
        redirect_to root_path, alert: 'Please, cheack in'
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize_user

  def new
    redirect_to users_show_user_path(session[:user_id]) if session[:user_id]
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      return redirect_to users_show_user_path(session[:user_id]) if user.role == 'user'
      return redirect_to users_show_admin_path(session[:user_id]) if user.role == 'admin'
    else
      redirect_to login_url, alert: 'Wrong login or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :authorize_user, only: [:index]
  before_action :set_task, only: [:edit, :update, :destroy, :show, :admin_show, :state_change]
  def new
    @task = Task.new
    redirect_to admin_new_path if @current_user.role == 'admin'
  end

  def admin_new
    @users = User.all.collect(&:email)
    @task = Task.new
  end

  def create
    @task = @current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to users_show_user_path(@current_user) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to users_show_user_path(@current_user) }
      else
        format.html { render :edit }
      end
    end
  end

  def edit
    redirect_to admin_edit_path if @current_user.role == 'admin'
  end

  def admin_edit
    @users = User.all.collect(&:email)
    @task = Task.find(params[:format])
  end

  def show
    redirect_to admin_show_path(id: @task.id) if @current_user.role == 'admin'
  end

  def admin_show
  end

  def destroy
    @task.destroy
    return render partial: 'destroy'
  end

  def index
    @tasks = Task.all
  end

  def state_change
    @task.update(state: params[:state])
    return render partial: 'form_state_change'
    # redirect_to users_show_admin_path(@current_user) if @current_user.role == 'admin'
    # redirect_to users_show_user_path(@current_user) if @current_user.role == 'user'
  end

    private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :name, :avatar, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show_user
    redirect_to users_show_admin_path(session[:user_id]) if @current_user.role == 'admin'
  end

  def show_admin
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            Menu <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand" href="index.html">Task Manager</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
            <li>
              <%= link_to "Exit", logout_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", login_path %>
            </li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
  <%= yield %>

</body>
</html>

app/views/tasks/_destroy.js.erb
$("#task_<%= @task.id %>").remove();
$("#divider_<%= @task.id %>").remove();

app/views/tasks/_form.html.slim
= simple_form_for @task do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.input :avatar, as: :file
  = f.hidden :iser_id, @task.user.id
  = f.button :submit

app/views/tasks/_form_for_admin.html.slim
= simple_form_for @task do |f|
  = f.input :name
  = f.input :description
  = f.input :user_id, collection: @users
  = f.button :submit

app/views/tasks/_form_state_change.js.erb
$("#task_<%= @task.id %>").remove();
$("#divider_<%= @task.id %>").remove();
$("#listing").append("<%=j render 'users/state_form', task: @task %>");

app/views/tasks/_state_change.js.erb
$("#task_form<%= @task.id %>").children().remove();

app/views/tasks/_state_form.html.slim
= form_tag('/state_change', remote: true) do
  = select_tag "state", options_for_select(Task.states.keys, selected: task.state), {class: 'tasky'}
  = hidden_field_tag("id", task.id)
  = submit_tag

app/views/tasks/admin_edit.html.slim
h1.taskListHeader Edit Task

= simple_form_for @task do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.input :user_id, collection: @users, selected: @task.user.email
  = f.input :avatar, as: :file
  = f.button :submit

app/views/tasks/admin_new.html.slim
h1.taskListHeader New Task

==render 'form_for_admin'

app/views/tasks/admin_show.html.slim
h1.taskListHeader Task


div.task_box
  div.task_item
    = @task.id
  div.task_item
    = @task.name
  div.task_item
    = @task.description
  div.task_item
    = @task.created_at.strftime('%H:%M:%S %Y-%m-%d')
  div.task_item
    = image_tag @task.avatar.url

app/views/tasks/edit.html.slim
h1.taskListHeader Edit Task

==render 'form'

app/views/tasks/index.html.slim
h1.taskListHeader Tasks list

- @tasks.each do |task|
  div.taskBox
    ul.taskLine
      li.taskAttr
        = task.id
      li.taskAttr
        = task.created_at.strftime('%H:%M:%S %Y-%m-%d')
      li.taskAttr
        = task.user.email
  hr.intro-divider

app/views/tasks/new.html.slim
h1.taskListHeader New Task

==render 'form'

app/views/tasks/show.html.slim
h1 Tasks#show
p Find me in app/views/tasks/show.html.slim

app/views/users/_state_form.html.slim
div.taskBox id="task_#{task.id}"
  ul.taskLine
    li.taskAttr
      = task.id
    li.taskAttr
      = task.user.email
    li.taskAttr
      = task.name
    li.taskAttr
      = task.description
    li.taskAttr id="task_form#{task.id}"
      = form_tag('/state_change', remote: true) do
        = select_tag "state", options_for_select(Task.states.keys, selected: task.state), {class: 'tasky', onchange: 'javascript: $( this ).trigger("submit.rails")'}
        = hidden_field_tag("id", task.id)
    li.taskAttr
      = task.created_at.strftime('%H:%M:%S %Y-%m-%d')
    li.taskAttr
      = image_tag task.avatar.url(:thumb)
    li.taskAttr.ruleTask
      = link_to 'Update', admin_edit_path(task), class: 'btn btn-primary'
      = link_to 'Destroy', task, data: { confirm: 'Are you sure' }, method: :delete, class: 'btn btn-primary', remote: true
      = link_to 'See', task_path(task), class: 'btn btn-primary'
hr.intro-divider id="divider_#{task.id}"

app/views/users/show_admin.html.slim
h1.taskListHeader Tasks list

.for_new_task_btn
  = link_to "New task", new_task_path, class: 'btn-lg btn-primary new_task_btn'
#listing
  - @tasks.each do |task|
    == render 'state_form', task: task

app/views/users/show_user.html.slim
h1.taskListHeader Tasks list

.for_new_task_btn
  = link_to "New task", new_task_path, class: 'btn-lg btn-primary new_task_btn'
- @current_user.tasks.each do |task|
  div.taskBox id="task_#{task.id}"
    ul.taskLine
      li.taskAttr
        = task.id
      li.taskAttr
        = task.name
      li.taskAttr
        = task.description
      li.taskAttr id="task_form#{task.id}"
        = form_tag('/state_change', remote: true) do
          = select_tag "state", options_for_select(Task.states.keys, selected: task.state), {class: 'tasky', onchange: 'javascript: $( this ).trigger("submit.rails")'}
          = hidden_field_tag("id", task.id)
      li.taskAttr
        = task.created_at.strftime('%H:%M:%S %Y-%m-%d')
      li.taskAttr
        = image_tag task.avatar.url(:thumb)
      li.taskAttr.ruleTask
        = link_to 'Update', edit_task_path(task), class: 'btn btn-primary'
        = link_to 'Destroy', task, data: { confirm: 'Are you sure' }, method: :delete, class: 'btn btn-primary', remote: true
        = link_to 'See', task_path(task), class: 'btn btn-primary'
  hr.intro-divider id="divider_#{task.id}"